### ISSUE TITLE
请大佬赏赐baiduyun链接

### ISSUE THREAD

**Issue by OneirdyniaYi** [JackeyLea/NJUCS#1]
大佬无论我是fork还是clone下载速度只有可怜的2kb/s。所以跪求百度云链接。

**Comment by JackeyLea** [comment]
按照我的经验，百度网盘也是几十kb/s，而且涉及文件位置调整，在百度网盘操作很麻烦，所以暂时不考虑百度网盘。如果本仓库所有内容稳定下来，只是每年更新新的资料的话会考虑上传到百度网盘。至少在2020-3月之前不会考虑百度网盘，望见谅。
