### ISSUE TITLE
老哥 群里有19真题啦，可以更新啦

### ISSUE THREAD

**Issue by RMfire** [JackeyLea/NJUCS#2]
感谢整理分享

**Comment by RMfire** [comment]
那个，打印版的真题里面是没有内容的吗，是原本就这样的吗

**Comment by JackeyLea** [comment]
19年真题已更新

**Comment by JackeyLea** [comment]
> 那个，打印版的真题里面是没有内容的吗，是原本就这样的吗

需要OCR，然后对照原版图片修正文字，然后调整细节。然后才会上传，暂时还是空白。现在已经只剩下16和17年了

**Comment by RMfire** [comment]
万分感谢！

**Comment by RMfire** [comment]
> > 那个，打印版的真题里面是没有内容的吗，是原本就这样的吗
> 
> 需要OCR，然后对照原版图片修正文字，然后调整细节。然后才会上传，暂时还是空白。现在已经只剩下16和17年了

万分感谢！
