### ISSUE TITLE
怎么全都没了？

### ISSUE THREAD

**Issue by wangyuxiang0829** [JackeyLea/NJUCS#6]
去哪里找之前的资料？

**Comment by JackeyLea** [comment]
重置的时候会把仓库清空，然后重新上传。以保证仓库内容不会太大，这次重置会把期末考试、模拟题等等都移到刷题软件中去。现在正常了吧。

**Comment by wangyuxiang0829** [comment]
> 重置的时候会把仓库清空，然后重新上传。以保证仓库内容不会太大，这次重置会把期末考试、模拟题等等都移到刷题软件中去。现在正常了吧。

请问参考书的参考答案跑哪去了，应该去哪里找
