### ISSUE TITLE
真题参考答案咋没了，还是想看看

### ISSUE THREAD

**Issue by XuenYat** [JackeyLea/NJUCS#8]

**Comment by JackeyLea** [comment]
因为有错误就删了

**Comment by XuenYat** [comment]
> 因为有错误就删了

主要想看看大题怎么答

**Comment by JackeyLea** [comment]
> > 因为有错误就删了
> 
> 主要想看看大题怎么答
去码云看看吧，那里还没有删除

**Comment by XuenYat** [comment]
> > > 因为有错误就删了
> > 
> > 
> > 主要想看看大题怎么答
> > 去码云看看吧，那里还没有删除

谢谢
